# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MLButton' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MLButton
  pod 'SnapKit'

  target 'MLButtonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MLButtonUITests' do
    # Pods for testing
  end

end
